//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 12:41:17 AM IST 
//


package com.combank.ips.outward.producer.model.camt_025_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import iso.std.iso._20022.tech.xsd.camt_025_001.LongPaymentIdentification2;
import iso.std.iso._20022.tech.xsd.camt_025_001.QueueTransactionIdentification1;
import iso.std.iso._20022.tech.xsd.camt_025_001.ShortPaymentIdentification2;


/**
 * <p>Java class for PaymentIdentification6Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentIdentification6Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TxId" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Max35Text"/>
 *         &lt;element name="QId" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}QueueTransactionIdentification1"/>
 *         &lt;element name="LngBizId" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}LongPaymentIdentification2"/>
 *         &lt;element name="ShrtBizId" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}ShortPaymentIdentification2"/>
 *         &lt;element name="PrtryId" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Max70Text"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentIdentification6Choice", propOrder = {
    "txId",
    "qId",
    "lngBizId",
    "shrtBizId",
    "prtryId"
})
public class PaymentIdentification6Choice {

    @XmlElement(name = "TxId")
    protected String txId;
    @XmlElement(name = "QId")
    protected QueueTransactionIdentification1 qId;
    @XmlElement(name = "LngBizId")
    protected LongPaymentIdentification2 lngBizId;
    @XmlElement(name = "ShrtBizId")
    protected ShortPaymentIdentification2 shrtBizId;
    @XmlElement(name = "PrtryId")
    protected String prtryId;

    /**
     * Gets the value of the txId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxId() {
        return txId;
    }

    /**
     * Sets the value of the txId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxId(String value) {
        this.txId = value;
    }

    /**
     * Gets the value of the qId property.
     * 
     * @return
     *     possible object is
     *     {@link QueueTransactionIdentification1 }
     *     
     */
    public QueueTransactionIdentification1 getQId() {
        return qId;
    }

    /**
     * Sets the value of the qId property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueTransactionIdentification1 }
     *     
     */
    public void setQId(QueueTransactionIdentification1 value) {
        this.qId = value;
    }

    /**
     * Gets the value of the lngBizId property.
     * 
     * @return
     *     possible object is
     *     {@link LongPaymentIdentification2 }
     *     
     */
    public LongPaymentIdentification2 getLngBizId() {
        return lngBizId;
    }

    /**
     * Sets the value of the lngBizId property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongPaymentIdentification2 }
     *     
     */
    public void setLngBizId(LongPaymentIdentification2 value) {
        this.lngBizId = value;
    }

    /**
     * Gets the value of the shrtBizId property.
     * 
     * @return
     *     possible object is
     *     {@link ShortPaymentIdentification2 }
     *     
     */
    public ShortPaymentIdentification2 getShrtBizId() {
        return shrtBizId;
    }

    /**
     * Sets the value of the shrtBizId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortPaymentIdentification2 }
     *     
     */
    public void setShrtBizId(ShortPaymentIdentification2 value) {
        this.shrtBizId = value;
    }

    /**
     * Gets the value of the prtryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtryId() {
        return prtryId;
    }

    /**
     * Sets the value of the prtryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtryId(String value) {
        this.prtryId = value;
    }

}
