//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 12:41:17 AM IST 
//


package com.combank.ips.outward.producer.model.camt_025_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import iso.std.iso._20022.tech.xsd.camt_025_001.PaymentInstrument1Code;


/**
 * <p>Java class for PaymentOrigin1Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentOrigin1Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="FINMT" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Max3NumericText"/>
 *         &lt;element name="XMLMsgNm" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Max35Text"/>
 *         &lt;element name="Prtry" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Max35Text"/>
 *         &lt;element name="Instrm" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}PaymentInstrument1Code"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentOrigin1Choice", propOrder = {
    "finmt",
    "xmlMsgNm",
    "prtry",
    "instrm"
})
public class PaymentOrigin1Choice {

    @XmlElement(name = "FINMT")
    protected String finmt;
    @XmlElement(name = "XMLMsgNm")
    protected String xmlMsgNm;
    @XmlElement(name = "Prtry")
    protected String prtry;
    @XmlElement(name = "Instrm")
    protected PaymentInstrument1Code instrm;

    /**
     * Gets the value of the finmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINMT() {
        return finmt;
    }

    /**
     * Sets the value of the finmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINMT(String value) {
        this.finmt = value;
    }

    /**
     * Gets the value of the xmlMsgNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLMsgNm() {
        return xmlMsgNm;
    }

    /**
     * Sets the value of the xmlMsgNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLMsgNm(String value) {
        this.xmlMsgNm = value;
    }

    /**
     * Gets the value of the prtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtry() {
        return prtry;
    }

    /**
     * Sets the value of the prtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtry(String value) {
        this.prtry = value;
    }

    /**
     * Gets the value of the instrm property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInstrument1Code }
     *     
     */
    public PaymentInstrument1Code getInstrm() {
        return instrm;
    }

    /**
     * Sets the value of the instrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInstrument1Code }
     *     
     */
    public void setInstrm(PaymentInstrument1Code value) {
        this.instrm = value;
    }

}
