//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 12:41:17 AM IST 
//


package com.combank.ips.outward.producer.model.camt_025_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import iso.std.iso._20022.tech.xsd.camt_025_001.MessageHeader9;
import iso.std.iso._20022.tech.xsd.camt_025_001.Receipt3;


/**
 * <p>Java class for ReceiptV05 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceiptV05">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgHdr" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}MessageHeader9"/>
 *         &lt;element name="RctDtls" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}Receipt3"/>
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:camt.025.001.05}SupplementaryData1" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiptV05", propOrder = {
    "msgHdr",
    "rctDtls"
})
public class ReceiptV05 {

    @XmlElement(name = "MsgHdr", required = true)
    protected MessageHeader9 msgHdr;
    @XmlElement(name = "RctDtls", required = true)
    protected Receipt3 rctDtls;

    /**
     * Gets the value of the msgHdr property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader9 }
     *     
     */
    public MessageHeader9 getMsgHdr() {
        return msgHdr;
    }

    /**
     * Sets the value of the msgHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader9 }
     *     
     */
    public void setMsgHdr(MessageHeader9 value) {
        this.msgHdr = value;
    }

    /**
     * Gets the value of the rctDtls property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt3 }
     *     
     */
    public Receipt3 getRctDtls() {
        return rctDtls;
    }

    /**
     * Sets the value of the rctDtls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt3 }
     *     
     */
    public void setRctDtls(Receipt3 value) {
        this.rctDtls = value;
    }

}
