//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 12:41:17 AM IST 
//


package com.combank.ips.outward.producer.model.camt_029_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvestigationStatus5Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvestigationStatus5Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Conf" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.10}ExternalInvestigationExecutionConfirmation1Code"/>
 *         &lt;element name="RjctdMod" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.10}ModificationStatusReason1Choice" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DplctOf" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.10}Case5" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="AssgnmtCxlConf" type="{urn:iso:std:iso:20022:tech:xsd:camt.029.001.10}YesNoIndicator" maxOccurs="0" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvestigationStatus5Choice", propOrder = {
    "conf"
})
public class InvestigationStatus5Choice {

    @XmlElement(name = "Conf")
    protected String conf;

    /**
     * Gets the value of the conf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConf() {
        return conf;
    }

    /**
     * Sets the value of the conf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConf(String value) {
        this.conf = value;
    }

}
