//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 12:41:17 AM IST 
//


package com.combank.ips.outward.producer.model.acmt_023_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import iso.std.iso._20022.tech.xsd.acmt_023_001.IdentificationAssignment2;
import iso.std.iso._20022.tech.xsd.acmt_023_001.IdentificationVerification2;


/**
 * <p>Java class for IdentificationVerificationRequestV02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationVerificationRequestV02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Assgnmt" type="{urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02}IdentificationAssignment2"/>
 *         &lt;element name="Vrfctn" type="{urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02}IdentificationVerification2"/>
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02}SupplementaryData1" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationVerificationRequestV02", propOrder = {
    "assgnmt",
    "vrfctn"
})
public class IdentificationVerificationRequestV02 {

    @XmlElement(name = "Assgnmt", required = true)
    protected IdentificationAssignment2 assgnmt;
    @XmlElement(name = "Vrfctn", required = true)
    protected IdentificationVerification2 vrfctn;

    /**
     * Gets the value of the assgnmt property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationAssignment2 }
     *     
     */
    public IdentificationAssignment2 getAssgnmt() {
        return assgnmt;
    }

    /**
     * Sets the value of the assgnmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationAssignment2 }
     *     
     */
    public void setAssgnmt(IdentificationAssignment2 value) {
        this.assgnmt = value;
    }

    /**
     * Gets the value of the vrfctn property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationVerification2 }
     *     
     */
    public IdentificationVerification2 getVrfctn() {
        return vrfctn;
    }

    /**
     * Sets the value of the vrfctn property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationVerification2 }
     *     
     */
    public void setVrfctn(IdentificationVerification2 value) {
        this.vrfctn = value;
    }

}
